version: 0.2

phases:
  build:
    commands:
      - echo "Packaging index-photos..."
      - zip -j index-photos.zip index-photos/lambda_function.py
      - echo "Updating index-photos Lambda..."
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip
      - echo "Packaging search-photos..."
      - zip -j search-photos.zip search-photos/lambda_function.py
      - echo "Updating search-photos Lambda..."
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
